server:
  port: 8088
  servlet:
    context-path: /springdemo
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssmtest?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis连接信息
  redis:
    host: localhost
    port: 6379
    # 无密码保护，请留空或删除这行配置
    password:
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 3000
mybatis:
  mapperLocations: classpath*:mapping/mybatis/*.xml
  typeAliasesPackage: com.example.springdemo.mybatis.entity