server:
  port: 8088
  servlet:
    context-path: /springdemo
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssmtest?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapperLocations: classpath*:mapping/mybatis/*.xml
  typeAliasesPackage: com.example.springdemo.mybatis.entity